### PR TITLE
Allow for Math::Ryu to accurately display "got" and "expected" NV values

### PR DESCRIPTION
**Pull request by sisyphus**
The following one-liner tests all fail, as they ought.
These have been run on a perl whose nvtype is double, but the same type of issue exists also for nvtypes of 'long double' and '__float128',
The issue is that the "got" and "expected" outputs absurdly indicate that the tests should have passed.

With Math::Ryu intervention the "got" and "expected" outputs indicate that the tests have, indeed, correctly reported FAIL.

With this PR, Math::Ryu intervention is then achieved seamlessly by simply installing Math::Ryu.
```
#######
CASE 1:

> perl -MTest::More -le "cmp_ok(0.1 ** 2, '==', 0.01, 'T1'); done_testing();"
$ perl -MTest::More -le 'cmp_ok(0.1 ** 2, "==", 0.01, "T1"); done_testing();'

Without Math::Ryu:

not ok 1 - T1
#   Failed test 'T1'
#   at -e line 1.
#          got: 0.01
#     expected: 0.01
1..1
# Looks like you failed 1 test of 1.

With Math::Ryu installed:

not ok 1 - T1
#   Failed test 'T1'
#   at -e line 1.
#          got: 0.010000000000000002
#     expected: 0.01
1..1
# Looks like you failed 1 test of 1.

#######
CASE 2:

> perl -MTest::More -le "$x = sqrt 2;cmp_ok(\"$x\", '==', $x, 'T2'); done_testing();"
$ perl -MTest::More -le '$x = sqrt 2;cmp_ok("$x", "==", $x, "T2"); done_testing();'

Without Math::Ryu:

not ok 1 - T2
#   Failed test 'T2'
#   at -e line 1.
#          got: 1.4142135623731
#     expected: 1.4142135623731
1..1
# Looks like you failed 1 test of 1.

With Math::Ryu installed:

not ok 1 - T2
#   Failed test 'T2'
#   at -e line 1.
#          got: 1.4142135623731
#     expected: 1.4142135623730951
1..1
# Looks like you failed 1 test of 1.

#######
CASE 3:

> perl -MTest::More -le "$x = sqrt 2;cmp_ok(\"$x\", '<=', $x, 'T3'); done_testing();"
$ perl -MTest::More -le '$x = sqrt 2;cmp_ok("$x", "<=", $x, "T3"); done_testing();'

Without Math::Ryu:

not ok 1 - T3
#   Failed test 'T3'
#   at -e line 1.
#     '1.4142135623731'
#         <=
#     '1.4142135623731'
1..1
# Looks like you failed 1 test of 1.

With Math::Ryu installed:

not ok 1 - T3
#   Failed test 'T3'
#   at -e line 1.
#     '1.4142135623731'
#         <=
#     '1.4142135623730951'
1..1
# Looks like you failed 1 test of 1.

#######
CASE 4:

> perl -MTest::More -le "$x = sqrt 2;cmp_ok($x, '>=', \"$x\", 'T4'); done_testing();"
$ perl -MTest::More -le '$x = sqrt 2;cmp_ok($x, ">=", "$x", "T4"); done_testing();'

Without Math::Ryu:

not ok 1 - T4
#   Failed test 'T4'
#   at -e line 1.
#     '1.4142135623731'
#         >=
#     '1.4142135623731'
1..1
# Looks like you failed 1 test of 1.

With Math::Ryu installed:

not ok 1 - T4
#   Failed test 'T4'
#   at -e line 1.
#     '1.4142135623730951'
#         >=
#     '1.4142135623731'
1..1
# Looks like you failed 1 test of 1.

#######
CASE 5:

> perl -MTest::More -le "cmp_ok(1.4/10, '!=', 0.13999999999999999, 'T5'); done_testing();"
$ perl -MTest::More -le 'cmp_ok(1.4/10, "!=", 0.13999999999999999, "T5"); done_testing();'

Without Math::Ryu:
The absurdity here is that (as perl well knows) 0.14 != 0.13999999999999999,
yet the displayed value for $got implies that 0.14 == 0.13999999999999999.

not ok 1 - T5
#   Failed test 'T5'
#   at -e line 1.
#          got: 0.14
#     expected: anything else
1..1
# Looks like you failed 1 test of 1.

With Math::Ryu installed:

not ok 1 - T5
#   Failed test 'T5'
#   at -e line 1.
#          got: 0.13999999999999999
#     expected: anything else
1..1
# Looks like you failed 1 test of 1.

#######
This issue doesn't arise all that often, but here's a recent example from
https://github.com/Perl/perl5/issues/22463 on 4th Aug 2024, from a
-Duselongdouble build of perl:

not ok 40 - tan(1) == -tan(-1)
#   Failed test 'tan(1) == -tan(-1)'
#   at ext/POSIX/t/math.t line 52.
#          got: 1.55740772465490223050697480745836
#     expected: 1.55740772465490223050697480745836

With this proposed use of Math::Ryu, that would have appeared as

not ok 40 - tan(1) == -tan(-1)
#   Failed test 'tan(1) == -tan(-1)'
#   at ext/POSIX/t/math.t line 52.
#          got: 1.55740772465490223050697480745836023
#     expected: 1.55740772465490223050697480745836081

#######
```
The correctness of the outputs relies on being able to firstly determine whether
$got and $expect (or $dont_expect) are, in fact, NVs.
Math::Ryu handles this itself - but if we wanted Test::More to make that assessment, then that could be arranged.

There are "alternative options" to Math-Ryu.
Let's look firstly at "%a" formatting:
```
>perl -le "printf '%a', 12345678.9;"
0x1.78c29dccccccdp+23
```
While "%a" formatting provides good accuracy, and can be easily applied acrossthe full range of nvtypes, we see in the above one-liner that readability suffers.
The magnitude of "0x1.78c29dccccccdp+23" is not assessed as easily and quickly as the magnitude of "12345678.9".
There is also the issue that "%a" formatting is not available prior to perl-5.22.
(I think we can pretty quickly eliminate that as a viable alternative.)

The other printf() formatting option is to use "%.17g" (for nvtype of 'double'),
"%.21g" (for the 80-bit extended precision long double nvtype) and "%.36g" (for
__float128 or IEEE-754 long double nvtypes).

The problem with that option is that it frequently obfuscates the value by showing more digits than serve a useful purpose.
The classic example would be: 
```
>perl -le "printf '%.17g', 0.1;"
0.10000000000000001
```
That's accurate, but no more accurate than simply "0.1" :

>perl -le "print 'equivalent' if 0.1 == 0.10000000000000001;"
equivalent

I'm not interested in implementing this fix using "printf".
I'd still patch my own builds of perl to utilize Math::Ryu even if that fix were applied.
Math::Ryu::nv2s() will never print out more decimal digits than are needed to accurately represent the value of the NV:
```
D:\>perl -MMath::Ryu=":all" -le "print nv2s(sqrt 2);"
1.4142135623730951

D:\>perl -MMath::Ryu=":all" -le "print nv2s(0.1);"
0.1
```
There's not much point in displaying "got" and "expected" values if they don't
represent the actual values - especially if they are so inaccurate as to imply an absurdity.

One deficiency with using Math::Ryu is that I've been unable to get it to build on 32-bit -Dusequadmath builds of perl.
AIUI, building the Ryu library to handle __float128 values requires that the compiler provides an unsigned int128_t type. But 32-bit compilers don't provide such a type.
(I expect the same problem arises on 32-bit perls whose nvtype is the IEEE 754 long double.)
There's no such issue with the 80-bit extended precision long double nvtype on either 32-bit or 64-bit perls.
And there's no problem with 64 bit builds, irrespective of nvtype.

Thoughts ?
Can this PR engage Math::Ryu::nv2s() when it should not ?
Are there cases where it ought to engage Math::Ryu::nv2s(), but fails
do so ?

I have limited this PR to dealing only with Test::More, but apparently Test2::V0 is also afflicted.
I would prefer Test2::V0 to be given the same treatment, but in a separate PR.
Some hints on precisely which pm file(s) would need to be amended might help me to get started on that.
Here's what I currently get with Test2::V0, for the above examples:
```
#######
> perl -MTest2::V0 -le "cmp_ok(0.1 ** 2, '==', 0.01, 'T1'); done_testing();"
$ perl -MTest2::V0 -le 'cmp_ok(0.1 ** 2, "==", 0.01, "T1"); done_testing();'

# Seeded srand with seed '20241029' from local date.
not ok 1 - T1
# Failed test 'T1'
# at -e line 1.
# +------+----+-------+
# | GOT  | OP | CHECK |
# +------+----+-------+
# | 0.01 | == | 0.01  |
# +------+----+-------+
1..1
#######
> perl -MTest2::V0 -le "my $x = sqrt 2;cmp_ok(\"$x\", '==', $x, 'T2'); done_testing();"
$ perl -MTest2::V0 -le 'my $x = sqrt 2;cmp_ok("$x", "==", $x, "T2"); done_testing();'

# Seeded srand with seed '20241029' from local date.
not ok 1 - T2
# Failed test 'T2'
# at -e line 1.
# +-----------------+----+-----------------+
# | GOT             | OP | CHECK           |
# +-----------------+----+-----------------+
# | 1.4142135623731 | == | 1.4142135623731 |
# +-----------------+----+-----------------+
1..1
#######
> perl -MTest2::V0 -le "my $x = sqrt 2;cmp_ok(\"$x\", '<=', $x, 'T3'); done_testing();"
$ perl -MTest2::V0 -le 'my $x = sqrt 2;cmp_ok("$x", "<=", $x, "T3"); done_testing();'

# Seeded srand with seed '20241029' from local date.
not ok 1 - T3
# Failed test 'T3'
# at -e line 1.
# +-----------------+----+-----------------+
# | GOT             | OP | CHECK           |
# +-----------------+----+-----------------+
# | 1.4142135623731 | <= | 1.4142135623731 |
# +-----------------+----+-----------------+
1..1
#######
> perl -MTest2::V0 -le "my $x = sqrt 2;cmp_ok($x, '>=', \"$x\", 'T4'); done_testing();"
$ perl -MTest2::V0 -le 'my $x = sqrt 2;cmp_ok($x, ">=", "$x", "T4"); done_testing();'

# Seeded srand with seed '20241029' from local date.
not ok 1 - T4
# Failed test 'T4'
# at -e line 1.
# +-----------------+----+-----------------+
# | GOT             | OP | CHECK           |
# +-----------------+----+-----------------+
# | 1.4142135623731 | >= | 1.4142135623731 |
# +-----------------+----+-----------------+
1..1
#######
> perl -MTest2::V0 -le "cmp_ok(1.4/10, '!=', 0.13999999999999999, 'T5'); done_testing();"
$ perl -MTest2::V0 -le 'cmp_ok(1.4/10, "!=", 0.13999999999999999, "T5"); done_testing();'
# Seeded srand with seed '20241029' from local date.
not ok 1 - T5
# Failed test 'T5'
# at -e line 1.
# +------+----+-------+
# | GOT  | OP | CHECK |
# +------+----+-------+
# | 0.14 | != | 0.14  |
# +------+----+-------+
1..1
#######
```

### CODE REVIEW

**Comment by exodist** [comment]
I am reluctant to change behavior in this way, specially for Test::More as it could lead to downstream failures where people do string comparisons of diagnostics to validate their own test tools. This is not a theory, this has bitten me several times.

That said There are hooks that allow you to write similar behavior as a plugin. The plugin would work for both Test2 and Test2::More Here is a script demonstrating:

```perl
use strict;
use warnings;

use Test::More;
require Test2::V0;
use Test2::API qw/test2_add_callback_context_acquire test2_add_callback_context_release/;

use Math::Ryu 'is_NV', 'nv2s';

BEGIN {
    my @ARGS;

    test2_add_callback_context_acquire(sub {
        my ($params) = @_; 

        package DB;
        my $level = 1;

        while (1) {
            my @caller = caller($level++);
            last unless @caller;

            if ($caller[3] =~ m/(is|cmp_ok)/) {
                my $oldargs = [@ARGS];
                @ARGS = @DB::args;

                $params->{on_release} = sub { @ARGS = @$oldargs };
            }   
        }   
    }); 

    my $hub = Test2::API::test2_stack()->top;

    $hub->filter(sub {
        my ($hub, $e) = @_; 

        return $e unless $e->causes_fail;

        my @nvs = grep { is_NV($_) } @ARGS;

        return $e unless @nvs;

        my $facets = $e->facet_data;

        push @{$facets->{info} //= []} => (
            {debug => 1, tag => 'Math Ryo', details => "Math::Ryo is providing more precise rendering of numbers from comparison:\n  " . join("\n  " => map { nv2s($_) } @nvs)},
        );  

        return Test2::Event::V2->new(%$facets);
    }); 
}

cmp_ok(0.1 ** 2, "==", 0.01, "T1");
Test2::V0::is(0.1 ** 2, Test2::V0::number(0.01), "T1");

done_testing();
```

The output is not quite as nice, but here it is:
```
not ok 1 - T1
# Math::Ryo is providing more precise rendering of numbers from comparison:
#   0.010000000000000002
#   0.01
#   Failed test 'T1'
#   at xxx.pl line 53.
#          got: 0.01
#     expected: 0.01
not ok 2 - T1

# Failed test 'T1'
# at xxx.pl line 54.
# +------+----+-------+-----+
# | GOT  | OP | CHECK | LNs |
# +------+----+-------+-----+
# | 0.01 | == | 0.01  | 54  |
# +------+----+-------+-----+
# Math::Ryo is providing more precise rendering of numbers from comparison:
#   0.010000000000000002
1..2
# Looks like you failed 2 tests of 2.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests 
```

The logic above can be written as a plugin like Test2::Plugin::MathRYU.
An example plugin can be found here: https://metacpan.org/release/EXODIST/Test-Simple-1.302204/source/lib/Test2/Plugin/UTF8.pm

You can take this code above and tweak it until it is more to your liking.

**Comment by exodist** [comment]
Oh also of note, with the facet_data you get the full table from the test2 events as a data structure, so you could modify the table directly to have 'GOT' show as the nv2s form. For Test::More you cannot easily modify the existing diag as it is a second event that comes after the ok event where ->causes_fail returns true.

**Comment by exodist** [comment]
Oh, some docs to help:
https://metacpan.org/pod/Test2::API#BEHAVIOR-HOOKS
https://metacpan.org/pod/Test2::API::Stack
https://metacpan.org/pod/Test2::Event::V2
https://metacpan.org/pod/Test2::Hub#ALTERING-OR-REMOVING-EVENTS
https://metacpan.org/pod/Test2::Manual::Tooling::Plugin::ToolStarts
https://perldoc.perl.org/functions/caller (for how @DB::args works)

**Comment by haarg** [comment]
While Ryu would be the nicest format to display these results in, it seems like it could be done with just a sprintf. This is only for failing tests, so performance is less of an issue. You could just try to format the numbers with increasing length until you find a difference.

**Comment by sisyphus** [comment]
> I am reluctant to change behavior in this way, specially for Test::More as it could lead to downstream failures where people do string comparisons of diagnostics to validate their own test tools. This is not a theory, this has bitten me several times.

FIrstly, note that this PR will lead to changed output only if Math::Ryu has been installed && $ENV{NO_USE_RYU} is unset.

I don't quite follow the problem of leading to "downstream failures".
It seems you are saying that if a Test::More diagnostic has been lying about the value of some NV, it must continue to present that same lie forever - otherwise people will complain that the diagnostic has changed.

Aaah ... hang on ... are you worried that (eg) "nan" might suddenly change to "NaN" and (eg) "inf" might suddenly become "Inf" ?
That's possible as I haven't taken steps to ensure that Math::Ryu's stringification of infs and nan matches perl's stringification in the local environment.
I'll attend to that before I do anything else. It's something that has been playing on my mind a bit, anyway.
(That's going to be fun with old perls on some systems.) 

If you're worried that (eg) "0.1" might change to "1e-1" or somesuch, then that sort of thing shouldn't happen.
With non-infnan values Math::Ryu will change the string only if the current string (as presented by Test::More) is inaccurate.
But I can see that this concern might have relevance if we started using "%.17g" formatting of double precision values.
That would definitely open the possibility that (eg) "0.1" changes to "0.10000000000000001" - which would be a change of diagnostic, without any change of value.

> You could just try to format the numbers with increasing length until you find a difference.

I think it's far more useful to have accurate representations of the values.
That way, anyone reading the report has a chance of working out how the test failure was arrived at.
But if inaccurate presentations are being provided, then all we can do is guess.

Thanks for the thoughts.
I'll take a look over the other information provide here, too, as time (and energy ;-) permit.

**Comment by haarg** [comment]
> > I am reluctant to change behavior in this way, specially for Test::More as it could lead to downstream failures where people do string comparisons of diagnostics to validate their own test tools. This is not a theory, this has bitten me several times.
> 
> FIrstly, note that this PR will lead to changed output only if Math::Ryu has been installed && $ENV{NO_USE_RYU} is unset.
> 
> I don't quite follow the problem of leading to "downstream failures". It seems you are saying that if a Test::More diagnostic has been lying about the value of some NV, it must continue to present that same lie forever - otherwise people will complain that the diagnostic has changed.

Just loading additional modules can lead to issues. In addition to itself, Math::Ryu loads B and DynaLoader.

> > You could just try to format the numbers with increasing length until you find a difference.
> 
> I think it's far more useful to have accurate representations of the values. That way, anyone reading the report has a chance of working out how the test failure was arrived at. But if inaccurate presentations are being provided, then all we can do is guess.

This applies to literally every time a number is printed in perl. I don't see why this is different in Test::More. The initial justification for this change is tests showing equivalent numbers after reporting them as different. Ryu is not needed to accomplish that goal.

I would support adding ryu style formatting to perl core, possibly as a sprintf format. But that's a different issue.

**Comment by sisyphus** [comment]
> Just loading additional modules can lead to issues. In addition to itself, Math::Ryu loads B and DynaLoader.

Maybe I should instead have written
```
unless($ENV{NO_USE_RYU}) {
as
if($ENV{USE_RYU}) {
```
That would have meant that the loading of Math::Ryu  (along with B and DynaLoader) would only happen if explicitly requested.
But I gather that even that would be too obtrusive for your liking.

> This applies to literally every time a number is printed in perl. I don't see why this is different in Test::More. 

No difference at all really. I usually use Math::Ryu to print NVs in perl.
I just thought that there might have been some general interest in an improvement in Test::More diagnostics.
It doesn't really matter to me ... I'll just keep patching things to suit myself.
Devel::Peek::Dump now uses  "%.17g" (or "%.21g" or "%.36g" where appropriate) to display the value held in an SV's NV slot.
That change in behaviour hasn't ruffled any feathers, AFAIK.

You are right of course in that the best thing is for the issue to be addressed in perl itself.
I honestly don't think that's going to happen in my lifetime ... but I'd be delighted to be proven wrong,

**Comment by exodist** [comment]
If you wrote it as `if($ENV{USE_RYU}) {`  then I would not object to this functionality. There would be no change unless someone asked for it, so things would not change unexpectedly.

In that case I would ask for an update to the Test2 tools as well, which would be in these locations:
https://github.com/Test-More/test-more/blob/master/lib/Test2/Compare/Number.pm#L32
https://github.com/Test-More/test-more/blob/master/lib/Test2/Compare/Float.pm#L49

Also may need something here that uses Math::Ryo when the comparison is numeric.
https://github.com/Test-More/test-more/blob/master/lib/Test2/Compare/Delta.pm#L126

I am not opposed to the functionality, just opposed to enabled by default.

**Comment by sisyphus** [comment]
> I am not opposed to the functionality, just opposed to enabled by default.

Ok - I'll make an another (new) PR when I've implemented your requested amendment and additions.
(I think I've deleted the branch for this PR .... and I'm a complete klutz with 'git', so a fresh attempt would be easiest for me.)

Thanks, @exodist

**Pull request closed without merging**
