### PR TITLE
Delay loading POSIX until it is needed

### PR DESCRIPTION
**Pull request by toddr**
Remove unnnecesary load of POSIX in Test2::IPC::Driver::Files

### CODE REVIEW

**Comment by toddr** [comment]
We apply this patch to our perl so I wanted to share it. POSIX can often be a heavy load. Any thoughts on including this patch?

**Comment by exodist** [comment]
Is the load-time for POSIX the only issue this is trying to resolve?

**Comment by exodist** [comment]
try_sig_mask is only used in one module. The module that uses try_sig_mask will ALWAYS use it if it gets loaded. Maybe move the try_sig_mask sub out of util and into Test2/IPC/Driver/Files.pm, and load POSIX there (not delayed). This way we do not have the require every time the sub is called, but we also only load POSIX when it will be needed.

**Comment by toddr** [comment]
> Is the load-time for POSIX the only issue this is trying to resolve?

We have an internal problem that POSIX is banned because of how heavy it is at runtime. As a result, we ban its use and probably it was breaking a test. This isn't your problem but I felt obligated to share the patch.

Feel free to close without merging.

**Comment by toddr** [comment]
> try_sig_mask is only used in one module. The module that uses try_sig_mask will ALWAYS use it if it gets loaded. Maybe move the try_sig_mask sub out of util and into Test2/IPC/Driver/Files.pm, and load POSIX there (not delayed). This way we do not have the require every time the sub is called, but we also only load POSIX when it will be needed.

That's also a good idea. Do you want to do it or should I submit the change?

**Comment by exodist** [comment]
How about you go ahead, and I will merge if it works right.

**Pull request merged**
