### PR TITLE
Stream/fix diag and note

### PR DESCRIPTION
**Pull request by exodist**

### CODE REVIEW

**Comment by exodist** [comment]
Surprisingly there were no legacy tests for this behavior in Test::More, there were for Test::Builder, but not Test::More.

**Comment by karenetheridge** [comment]
would it be possible to make the MANIFEST and Changes updates in the same commit? this makes it a lot easier down the road when looking at history.

**Comment by exodist** [comment]
sure

**Comment by exodist** [comment]
I will merge manually and squash them together

**Comment by exodist** [comment]
merged manually and squashed.

**Pull request closed without merging**
